name: FTP Deploy to onitel.co.za

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "Configure prod - ftp deployment"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Check secrets existence
        run: |
          echo "FTP_HOST: ${FTP_HOST:+set}"
          echo "FTP_USERNAME: ${FTP_USERNAME:+set}"
          echo "FTP_PASSWORD: ${FTP_PASSWORD:+set}"
          echo "FTP_REMOTE_PATH: ${FTP_REMOTE_PATH:+set}"

      - name: Build the project
        run: npm run build

      - name: Verify dist folder
        run: ls -la ./dist

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote-dir: ${{ secrets.FTP_REMOTE_PATH }}
          local-dir: ./dist
          clean: true
